/**********************************************************************************************
 *
 *     .oooooo.                                    oooooooooooo  .oooooo..o   .oooooo.
 *    d8P'  `Y8b                                   `888'     `8 d8P'    `Y8  d8P'  `Y8b
 *   888      888 oo.ooooo.   .ooooo.  ooo. .oo.    888         Y88bo.      888
 *   888      888  888' `88b d88' `88b `888P"Y88b   888oooo8     `"Y8888o.  888
 *   888      888  888   888 888ooo888  888   888   888    "         `"Y88b 888
 *   `88b    d88'  888   888 888    .o  888   888   888       o oo     .d8P `88b    ooo
 *    `Y8bood8P'   888bod8P' `Y8bod8P' o888o o888o o888ooooood8 8""88888P'   `Y8bood8P'
 *                 888
 *                o888o                                                 (MJM 5-15-2024)
 *
 *   Wrote from the EPSON TM-T90 Technical Specification
 *
 *   File: font_mono.h
 *   Note: none
 *
 *********************************************************************************************/

 //
 // Bitmap font C source generated by bmfont2c.py 
 // 
 // Filename    : bmfont2c.py
 // Description : Converts bitmap font(s) generated by BMFont to C code
 // Author : Lars Ole Pontoppidan, 2014
 // URL : http ://larsee.dk/ 
 // 

#pragma once

#include <cstdint>

typedef struct {
    uint8_t GlyphCount;
    uint8_t FirstAsciiCode;
    uint8_t GlyphBytesWidth;
    uint8_t GlyphHeight;
    uint8_t FixedWidth;
    uint8_t const* GlyphWidth;
    uint8_t const* GlyphBitmaps;
} fontStyle_t;

extern fontStyle_t FontStyle_mono_one_17x8;
extern fontStyle_t FontStyle_mono_one_24x12;